import os
import openai
user_api_key = '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'
os.environ["OPENAI_API_KEY"] = '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'

